/*   Error and status messages relating to the MDEV library.
/*
msg err1
  lan english -def
    Sharing of interface %p2s by module %p1s on line %p3i of file "%p4s"
    is inconsistent with a previous declaration.
msg err2
  lan english -def
    Interface "%p1s" is undefined.
msg err3
  lan english -def
    Interface "%p1s" is undefined, referenced by firmware "%p2s".
msg err4
  lan english -def
    Interface "%p1s" is undefined, referenced by module "%p2s".
